name: update-schema-data

on: 
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: npm

      - name: Check upstream pint schema
        run: npm run schema

      - name: Check the retrieved file for curl error messages.
        run: |
          node -e "const fs = require('node:fs'); if (fs.readFileSync('./schemas/pint-schema.json', { encoding: 'utf8' }).split('\n').length === 1) console.log('NG'); process.exit(1);"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'ci(schema): update'
          commit-message: 'ci(schema): update'
          author: 'GitHub <noreply@github.com>'
          delete-branch: true
