name: upstream-schema-check

on: 
  #schedule:
  #  - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: npm

      - name: Check upstream pint schema
        run: node scripts/check-upstream-pint-schema.mjs
